#!/bin/bash

#Settings
localSitePath="/private/var/www/local.website"
localFilePath=${localPath#"$localSitePath"}
remotePath="/remote/server/path/www/website"	
filePath=$1

#Colors
Red='\033[0;31m'
LightGreen='\033[1;32m'
Default='\033[0m' 

getRelativePath (){ 
  filePathLength=${#filePath}
  localSitePathLength=${#localSitePath}    
  relativePath=${filePath: $localSitePathLength: filePathLength}
}

getParentDirectory () { 
  getRelativePath 
  parentPath=${relativePath%/*}  
}

unHappyFace () {
  echo "¯\_(′︿‵｡)_/¯";
}

upLoadTheFile () {
  getRelativePath 
  printf "${LightGreen} Uploading: ${Default} $filePath \n"
  printf "${LightGreen} To Server:  ${Default} $remotePath$relativePath  \n" 
  scp $filePath   $remotePath$relativePath 
}

upLoadTheDirectory (){
  getRelativePath
  getParentDirectory
  printf "${LightGreen} Uploading Dir: ${Default} $filePath \n"
  printf "${LightGreen} To Server Dir: ${Default} $remotePath$parentPath  \n" 
  scp -r $filePath  $remotePath$parentPath  
}

if [[ -d $filePath ]]; then
    upLoadTheDirectory
elif [[ -f $filePath ]]; then 
    upLoadTheFile  
else 
    printf "File or Directory doesn't exist"
    echo " "
    unHappyFace
    exit 1
fi 